/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Business.EcoSystem;
import Business.Role.DonorAdminRole;
import Business.Role.DonorRole;
import Business.Role.HospitalAdminRole;
import model.jdbcConnection;
import ui.Doctor.DoctorAreaJPanel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import ui.Doctor.addPatient;
import ui.DonorAdmin.DonorAdminJPanel;
import ui.Sysadmin.SysAdminPanel;
import Business.Role.SysAdminRole;



/**
 *
 * @author kashr
 */
public class MainJFrame extends javax.swing.JFrame {

    private EcoSystem system;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        initializeSystem();
    }
    
    void initializeSystem(){
        system = EcoSystem.getInstance();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        LoginjPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        logoutJButton = new javax.swing.JButton();
        jpswd = new javax.swing.JPasswordField();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        jpswd.setText("jPasswordField1");

        javax.swing.GroupLayout LoginjPanelLayout = new javax.swing.GroupLayout(LoginjPanel);
        LoginjPanel.setLayout(LoginjPanelLayout);
        LoginjPanelLayout.setHorizontalGroup(
            LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginjPanelLayout.createSequentialGroup()
                .addGroup(LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LoginjPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginjPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpswd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        LoginjPanelLayout.setVerticalGroup(
            LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginjPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LoginjPanelLayout.createSequentialGroup()
                        .addGroup(LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(logoutJButton)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(LoginjPanel);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(container);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String[] arr = system.getConnection().getRole(txtUserName.getText(),String.valueOf(jpswd.getPassword()));
        if(arr[1].equalsIgnoreCase("doctor"))
        { DoctorAreaJPanel doctorPanel = new DoctorAreaJPanel();
            jSplitPane2.setRightComponent(doctorPanel);
        }
        if(arr[1].equalsIgnoreCase("donoradmin")) {
            DonorAdminRole aRole = new DonorAdminRole();
            CardLayout layout = (CardLayout)container.getLayout();            
            container.add("workarea", aRole.createWorkArea(container, this.system, arr[0]));
            layout.next(container);
        }

        if(arr[1].equalsIgnoreCase("donor")) {
            DonorRole aRole = new DonorRole();
            CardLayout layout = (CardLayout)container.getLayout();            
            container.add("donorworkarea", aRole.createWorkArea(container, this.system, arr[0]));
        }

         if(arr[1].equalsIgnoreCase("sysadmin")) {
            SysAdminRole aRole = new SysAdminRole();
            CardLayout layout = (CardLayout)container.getLayout();            
            container.add("workarea", aRole.createWorkArea(container, this.system, arr[0]));
            layout.next(container);
        }
                      if(arr[1].equalsIgnoreCase("hospitaladmin")) {
            HospitalAdminRole aRole = new HospitalAdminRole();
            CardLayout layout = (CardLayout)container.getLayout();            
            container.add("workarea", aRole.createWorkArea(container, this.system, arr[0]));

            layout.next(container);
        }
        
        logoutJButton.setEnabled(true);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
    
        jButton2.setEnabled(true);
        txtUserName.setText("");
        jpswd.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        logoutJButton.setEnabled(false);    
        
        
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:

//        jdbcConnection connection = new jdbcConnection();
//        String values[] = connection.getRole(jTextField1.getText(),String.valueOf(jPasswordField1.getPassword()));
//        if(values[0] == "doctor")
//        {
//        }
//    }                                        

    }                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginjPanel;
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPasswordField jpswd;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
